In [1]:
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])
df["class"] = iris.target
cov=df.iloc[:, 0:4].cov()
cor=df.iloc[:, 0:4].corr()
print("Covariance:\n",cov)
print("\nCorelation:\n",cor)

Covariance:
               sepal_length  sepal_width  petal_length  petal_width
sepal_length      0.685694    -0.042434      1.274315     0.516271
sepal_width      -0.042434     0.189979     -0.329656    -0.121639
petal_length      1.274315    -0.329656      3.116278     1.295609
petal_width       0.516271    -0.121639      1.295609     0.581006

Corelation:
               sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000


In [2]:
import numpy as n
import tensorflow as t

s=50
print("Scalar : ",s)

m=n.array([[0, 2],[2, 3]])
v=n.array([[0, 2]])
print("\nMatrix:\n",m)
print("\nVector:\n",v)

print("\nTensor:")
fill_2d = t.fill([3, 3],4, '2d')
fill_string = t.fill([2, 2], "str", 'fill_tensor_string')
print("\nNumerics:\n",fill_2d)
print("\nString:\n",fill_string)

g=n.gradient(m)
print("\nGradient:\n",g)

w,v = n.linalg.eig(m)
mat_norm = n.linalg.norm(m)
print("\nEigen values:\n",w)
print("\nEigen vectors:\n",v)
print("\nMatrix norm:", mat_norm)


Scalar :  50

Matrix:
 [[0 2]
 [2 3]]

Vector:
 [[0 2]]

Tensor:

Numerics:
 tf.Tensor(
[[4 4 4]
 [4 4 4]
 [4 4 4]], shape=(3, 3), dtype=int32)

String:
 tf.Tensor(
[[b'str' b'str']
 [b'str' b'str']], shape=(2, 2), dtype=string)

Gradient:
 [array([[2., 1.],
       [2., 1.]]), array([[2., 2.],
       [1., 1.]])]

Eigen values:
 [-1.  4.]

Eigen vectors:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]

Matrix norm: 4.123105625617661
